name: superproject cmake

on:
  push:
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Boost superproject
      run: |
        cd ..
        git clone -b $GITHUB_BASE_REF --depth 5 https://github.com/boostorg/boost.git
        cd boost
        git submodule update --init --depth 5
        rm -rf libs/histogram/*
        mv -f $GITHUB_WORKSPACE/* libs/histogram
        mv -f * $GITHUB_WORKSPACE
    - name: CMake from superproject
      run: |
        cd ..
        cmake -DBoost_VERBOSE=1 $GITHUB_WORKSPACE
        cmake --build . --target all -j3 -- -k
